# =====================================================================
# AUTH-SERVER-CORE Configuration
# =====================================================================
spring.application.name=user-sec

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sec
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Auth Configuration
auth.refresh-token.expiry-hours=720
auth.lockout.max-attempts=5
auth.lockout.duration-minutes=30
auth.mfa.issuer=YourAppName

# Logging
logging.level.com.pranav.authcore=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
